# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-22 06:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=16, validators=(django.core.validators.RegexValidator('\\+?\\d+'),), verbose_name='Contact phone'),
        ),
    ]
